### ISSUE TITLE
Validator is broken

### ISSUE THREAD

**Issue by DanielHreben** [asholok/python-validator-livr#12]
Unless I miss something, v2.0 is completely broken:

```
Command failed: ./validate.py {} {}
Traceback (most recent call last):
  File "/home/<USER>/.local/lib/python3.4/site-packages/LIVR/Validator.py", line 2, in <module>
    import BuildAliasedRule
ImportError: No module named 'BuildAliasedRule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./validate.py", line 3, in <module>
    from LIVR import Validator
  File "/home/<USER>/.local/lib/python3.4/site-packages/LIVR/Validator.py", line 8, in <module>
    from . import DEFAULT_RULES
  File "/home/<USER>/.local/lib/python3.4/site-packages/LIVR/DEFAULT_RULES.py", line 6, in <module>
    import Common
  File "/home/<USER>/.local/lib/python3.4/site-packages/LIVR/Rules/Common.py", line 2, in <module>
    import constants
  File "/home/<USER>/.local/lib/python3.4/site-packages/LIVR/Rules/constants.py", line 4, in <module>
    PRIMITIVE_LIST = NUMBER_LIST + (str, bool, unicode)
NameError: name 'unicode' is not defined

```
See http://livr-multi-playground.webbylab.com/

Maybe python v3 issue?

**Comment by asholok** [comment]
yes i forgot it in python 3 unicode deprecated. Ill fix it. Thx

**Comment by DanielHreben** [comment]
```
Downloading/unpacking livr (from -r requirements.txt (line 1))
  Downloading LIVR-2.0.tar.gz
  Running setup.py (path:/tmp/pip-build-sm_jmm1_/livr/setup.py) egg_info for package livr

Installing collected packages: livr
  Running setup.py install for livr
      File "/home/webbylab/.local/lib/python3.4/site-packages/LIVR/Rules/Numeric.py", line 22
        except ValueError, e:
                         ^
    SyntaxError: invalid syntax
```

**Comment by asholok** [comment]
LIVR-2.0.1.tar.gz must be. Are you sure that v 2.0.1 installed

**Comment by DanielHreben** [comment]
Looks like 2.0.1 is not available via pip
```
pip3 install 'livr>=2.0.1'
Downloading/unpacking livr>=2.0.1
  Could not find a version that satisfies the requirement livr>=2.0.1 (from versions: 0.4.22, 0.4.22, 0.4.1, 0.4.1, 2.0, 0.4.31, 0.4.31)
```

**Comment by asholok** [comment]
https://pypi.python.org/pypi?name=LIVR&version=2.0.1&:action=display
```
asholok@asholok-V:~/St/GitHub/python-validator-livr$ sudo pip install LIVR
Downloading/unpacking LIVR
  Downloading LIVR-2.0.1-py2-none-any.whl
Installing collected packages: LIVR
Successfully installed LIVR
Cleaning up...
```
I think better use ``` pip install LIVR ``` if it possible

**Comment by asholok** [comment]
Before I find out how port to pip3 :)

**Comment by asholok** [comment]
@SDSWanderer try again plz

**Comment by DanielHreben** [comment]
It works now, thanks!
