### ISSUE TITLE
Having issues w/ python3.4 and virtualenv

### ISSUE THREAD

**Issue by anxolerd** [asholok/python-validator-livr#2]
Is this package python3-ready? Cause I have issues using it w/ python3.4

my steps:

``` bash
$ virtualenv -p python3.4 env3
$ . ./env3/bin/activate
(env3) $ pip install LIVR
(env3) $ python
Python 3.4.3 (default, Mar 28 2015, 18:58:44) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from LIVR import Validator
```

expected result: no errors
actual result:

``` python
>>> from LIVR import Validator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/workspace/project/env3/lib/python3.4/site-packages/LIVR/Validator.py", line 1, in <module>
    import BuildAliasedRule
ImportError: No module named 'BuildAliasedRule'
```

meanwhile there are no troubles w/ python 2.7

If there is no python3 version, could you please provide it?

**Comment by asholok** [comment]
Ok thx. I'll find what I can do. But at the weekend.

**Comment by asholok** [comment]
Fixed in new release. Please try it.
