### ISSUE TITLE
Error on import, validator completely broken now

### ISSUE THREAD

**Issue by DanielHreben** [asholok/python-validator-livr#4]
Ubuntu 15.04 x64.
Same error on 2 and 3 version of python:

``` sh
pip install LIVR
Downloading/unpacking LIVR
  Downloading LIVR-0.4.21-py2.py3-none-any.whl
Installing collected packages: LIVR
Successfully installed LIVR
Cleaning up...
```

``` sh
python                         
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from LIVR import Validator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wanderer/.local/lib/python2.7/site-packages/LIVR/Validator.py", line 6, in <module>
    from . import DEFAULT_RULES
  File "/home/wanderer/.local/lib/python2.7/site-packages/LIVR/DEFAULT_RULES.py", line 11, in <module>
    import Helper
  File "/home/wanderer/.local/lib/python2.7/site-packages/LIVR/Rules/Helper.py", line 3, in <module>
    import internal_reactor
ImportError: No module named internal_reactor
>>> 
```

**Comment by asholok** [comment]
Wooh thanks for quick react! Try now.

**Comment by DanielHreben** [comment]
Sure, fixed.
Python realisation [seems close to others right now](http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5Btrue%2C%20false%5D%7D%2C%5Cn%20%20login%3A%20'email'%2C%5Cn%20%20link%3A%20'url'%2C%5Cn%20%20list%3A%20%7Blist_of%3A%20%5B%7Bnested_object%3A%20%7B%7D%7D%5D%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20flag%3A%20true%2C%5Cn%20%20login%3A%20'a%20%40gmail.com'%2C%5Cn%20%20link%3A%20'http%3A%2F%2Fgoogle'%2C%5Cn%20%20list%3A%20%5B%5B%5D%5D%5Cn%7D%22%7D)
